apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
spec:
  secretName: tls-rancher-ingress
  commonName: unixsre.com
  dnsNames:
  - unixsre.com
  - "*.unixsre.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
